.TH MATHMINI 1 "September 2023"
.SH NAME
mathmini \- a simple mathematical operations program
.SH SYNOPSIS
\fBmathmini\fR [\fIoperation\fR] [\fIa\fR] [\fIb\fR]
.SH DESCRIPTION
\fBmathmini\fR is a program that performs basic mathematical operations on two integers.
.SH OPTIONS
\fBmathmini\fR supports the following operations:
.TP
\fBadd\fR
Perform addition operation.
.TP
\fBsub\fR
Perform subtraction operation.
.SH EXAMPLES
To add two numbers:
.PP
\fBmathmini add 10 5\fR
.PP
To subtract two numbers:
.PP
\fBmathmini sub 10 5\fR
